apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-service-v2
  labels:
    app: helloworld-service
    version: "2.0"
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld-service
      version: "2.0"
      serving: "true"
  template:
    metadata:
      labels:
        app: helloworld-service
        version: "2.0"
        serving: "true"
        visualize: "true"
    spec:
      containers:
      - name: helloworld-service
        image: bygui86/guestbook-example/helloworld-service-java:latest
        env:
        - name: VERSION
          value: "2.0"
        - name: GREETING
          value: "Hola $name from $hostname version $version"
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /hello/ready
            port: 8080
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 400m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 1000Mi

