
spring:
  application:
    name: guestbook-service
    rest:
      base-path: /api
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/app?autoReconnect=true
    username: root
    password: yourpassword
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      generate-ddl: true
      ddl-auto: update
      globally_quoted_identifiers: true
  sleuth:
    propagation-keys: x-request-id,x-ot-span-context
