apiVersion: v1
kind: ConfigMap
metadata:
  name: helloworld-service-v2
  labels:
    app: helloworld-service
data:
  HELLOSVC_KUBE_HOST: "0.0.0.0"
  HELLOSVC_MONITOR_HOST: "0.0.0.0"
  HELLOSVC_REST_HOST: "0.0.0.0"
  HELLOSVC_REST_GREETING: "Ciao %s da %s su %s"
  HELLOSVC_REST_VERSION: "2.0"
