apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-service-v1
  labels:
    app: guestbook-service
    version: "1.0"
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-service
      version: "1.0"
      serving: "true"
  template:
    metadata:
      labels:
        app: guestbook-service
        serving: "true"
        version: "1.0"
        visualize: "true"
    spec:
      containers:
      - name: guestbook-service
        image: bygui86/guestbook-example/guestbook-service:latest
        livenessProbe:
          initialDelaySeconds: 90
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 400m
            memory: 500Mi
          limits:
            cpu: 1500m
            memory: 1000Mi
