apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      version: "4.0.2"
  template:
    metadata:
      labels:
        app: redis
        version: "4.0.2"
        visualize: "true"
    spec:
      containers:
      - name: redis
        image: redis:4.0.2
        livenessProbe:
          tcpSocket:
            port: 6379
        ports:
        - name: redis-server
          containerPort: 6379
        resources:
          requests:
            cpu: 400m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 2000Mi
