kind: Service
apiVersion: v1
metadata:
  name: guestbook-ui
  labels:
    app: guestbook-ui
    visualize: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: guestbook-ui
    serving: "true"
